#ifndef OPENDSTR_VERSION_H
#define OPENDSTR_VERSION_H

#define FIRMWARE_VERSION_MAJOR 0
#define FIRMWARE_VERSION_MINOR 2
#define FIRMWARE_VERSION_PATCH 0
#define FIRMWARE_VERSION_STR "v0.2.0"

#endif //OPENDSTR_VERSION_H
